version: '3'

services:
  apache:
    image: arm64v8/httpd:2.4
    container_name: raspberry_apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/ssl:/usr/local/apache2/ssl
      - ./apache/extra:/usr/local/apache2/conf/extra
    restart: always
    environment:
      - TZ=America/Santiago
    networks:
      - web_network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M

  ftp:
    image: delfer/alpine-ftp-server:latest
    container_name: raspberry_ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./ftp/folders:/ftp/upload
      - ./ftp/logs:/var/log/vsftpd
      - ./ftp/start.sh:/start.sh
    environment:
      - USERS=ftpuser|ftppassword123|/ftp/upload
      - ADDRESS=192.168.4.64 #Revisar esto
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - LOG_STDOUT=true
    restart: always
    networks:
      - web_network
    depends_on:
      - apache

networks:
  web_network:
    driver: bridge